[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vaultplex = "9a8aV7w4h7xpoFKnCuXvwef3pXexBbeJBUmMh79sQ5xb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
